### ISSUE TITLE
Verificar o conflito de horários considerando as datas de início e término das disciplinas

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#1]
O MatrUSP verifica o conflito entre turmas e disciplinas comparando apenas os horários e os dias de oferecimento. Há disciplinas, na Medicina por exemplo, que duram menos de um semestre e os alunos podem fazer matrículas sem conflitos de horários graças às diferenças nas datas de início e término de cada disciplina.

Na Poli, há turmas de laboratório com aulas quinzenais. É possível fazer matrícula em duas turmas com o "mesmo horário", uma com aulas nas semanas pares e outras nas semanas ímpares.

**Comment by Samlibardi** [comment]
Infelizmente não há nenhuma maneira confiável de identificar disciplinas quinzenais. Algumas disciplinas em São Carlos ([SLC0663](https://uspdigital.usp.br/jupiterweb/obterTurma?sgldis=SLC0663), [SLC0629](https://uspdigital.usp.br/jupiterweb/obterTurma?sgldis=SLC0629), [7600109](https://uspdigital.usp.br/jupiterweb/obterTurma?sgldis=7600109) por exemplo) possuem a identificação da quinzena, o que permite que essas disciplinas sejam tratadas corretamente. No entanto, o laboratório [4300254](https://uspdigital.usp.br/jupiterweb/obterTurma?sgldis=4300254) do IF, por exemplo, parece ser quinzenal mas não há nenhuma indicação nas informações de turma/disciplina. Inclusive, o número de créditos e carga horária são condizentes com uma disciplina semanal, não quinzenal.
