### ISSUE TITLE
Diversos arquivos .scss requisitados resultando em erros 404

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#11]
Testado no MS Edge

![image](https://cloud.githubusercontent.com/assets/577970/19336181/3e0cd648-90be-11e6-91b0-489ead2fdbf8.png)

**Comment by Samlibardi** [comment]
Acho que isso já foi resolvido. Nunca observei e acho improvável que os arquivos do Sass sejam pedidos pelo navegador, uma vez que só o css está listado no HTML.
