### ISSUE TITLE
Exceção ao fazer upload de arquivo inválido

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#13]
1. Clique em Upload de Grade
2. Faça o upload de algum arquivo inválido. Uma imagem, documento, etc.

Experado: O usuário é informado que o arquivo é inválido

Real: State.prototype.uploadFile lança uma exceção:

![image](https://cloud.githubusercontent.com/assets/577970/19336312/0e3088d8-90bf-11e6-93cf-07839aa4d257.png)

**Comment by Samlibardi** [comment]
Já corrigido. Esta exceção é capturada e um banner é exibido na tela.
