### ISSUE TITLE
Identificadores diferentes são gerados para a mesma grade

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#16]
1. Monte uma grade no MatrUSP
2. Clique repetidas vezes em Enviar por Email

Esperado: No máximo um identificador deveria ser gerado por sessão. Caso o usuário altere a grade, o cliente sobrescreveria o conteúdo armazenado no servidor para o identificador auto-gerado.

**Comment by brunoendo** [comment]
Pedro corrigi isso, quando puder da uma olhada no gh-pages que eu subo, vlw!

**Comment by pedropaulovc** [comment]
Confirmado que apenas um identificador é gerado. Porém, isto causou uma regressão: #26
