### ISSUE TITLE
Exceção clicar no botão "+"

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#18]
1. Clique no botão "+" sem preencher o campo de nome de disciplina

Esperado: Nenhuma exceção deveria ser gerada

Real:

![image](https://cloud.githubusercontent.com/assets/577970/19336560/4f6af55c-90c1-11e6-917e-afef3fd45e4b.png)

**Comment by pedropaulovc** [comment]
Outros cenários que também lançam exceção:

1. Nome de disciplina inválido
2. Código de disciplina (testado com 'MAE1511')

**Comment by Samlibardi** [comment]
Este botão já não faz mais parte do layout, então acho que esta issue pode ser fechada.
