### ISSUE TITLE
Dropdown para escolha de disciplinas não funciona com o teclado

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#19]
1. Faça uma busca por uma disciplina na caixa de busca
2. Aperte seta para baixo

Esperado: Você pode escolher uma displina usando o teclado

Atual: Seta para baixo não gera nenhum efeito. Tab faz o dropdown fechar.

**Comment by pedropaulovc** [comment]
On Oct 13, 2016 4:58 AM, "brunoendo" <notifications@github.com> wrote:
>
> Oi Pedro, esse bug acontece em algum navegador específico ?

Testei no Edge, última versão.

> Testei no Chrome e funciona do jeito esperado. Além disso, qual deveria
ser o comportamento do Tab ?

Eu diria que se você tiver alguma matéria selecionada, esta seleção seria
colocada na caixa de texto, o drop down fecharia e o foco moveria para o
botão "+". Caso contrário, apenas fechar o drop down e mover o foco pro
botão +.

**Comment by Samlibardi** [comment]
Já funciona na versão atual, não tenho certeza quando foi implementado.
