### ISSUE TITLE
Separar turmas teóricas e práticas na escolha de disciplinas

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#2]
Há disciplinas que tem aulas teóricas e aulas prática. Ex: [6022010](https://uspdigital.usp.br/jupiterweb/jupTurma?sgldis=6022010), [LEB0450](https://uspdigital.usp.br/jupiterweb/jupTurma?sgldis=LEB0450), etc. Habitualmente o Jupiter indica qual turma prática está associada a qual turma teórica, o que permite gerar um JOIN com os horários das duas partes. Porém, às vezes esta informação não está disponível e o comportamento atual do MatrUSP é simplesmente listar todas as turmas teóricas e práticas dentro da mesma disciplina. No momento cada grade horária gerada pelo MatrUSP inclui apenas uma turma por disciplina, o que é um problema neste caso.

Uma solução é, para cada disciplina com parte teórica e prática, quebrá-la em três:
- AAA0001 (T) - Disciplina A, Turmas de parte teórica
- AAA0001 (P) - Disciplina A, Turmas de parte prática
- AAA0001 (T+P) - Disciplina A, Turmas de parte teórica + prática

Quando for possível fazer todos os JOINs, as disciplinas (T) e (P) não devem ser exibidas.

**Comment by Samlibardi** [comment]
Na versão atual, é possível adicionar mais uma vez a mesma disciplina, assim é possível selecionar mais de uma turma ao mesmo tempo.
