### ISSUE TITLE
[Edge] Barra de rolagem aparece ao limpar caixa de busca de disciplinas

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#20]
1. No Edge
2. Busque por uma disciplina
3. Apague o texto

Experado: Nada deveria mudar na UI

Real:

![image](https://cloud.githubusercontent.com/assets/577970/19336703/77e07ccc-90c2-11e6-99f5-98b2c74dafa4.png)

**Comment by Samlibardi** [comment]
Já corrigido. Fechando
