### ISSUE TITLE
Link gerado por botão Enviar por Email não funciona

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#22]
1. No Edge
2. Monte uma grade horária
3. Clique em Enviar por Email. Copie o link.
4. Abra uma janela incognito. Cole o link

Esperado: A grade horária deveria abrir

Real: O MatrUSP abre vazio

**Comment by brunoendo** [comment]
Pedro, quando puder da uma olhada que acho que está corrigido.

**Comment by pedropaulovc** [comment]
Confirmado
