### ISSUE TITLE
Carregar um identificador não funciona

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#23]
1. No Edge
2. Monte uma grade horária
3. Clique em Enviar por Email. Copie o identificador.
4. Abra uma janela incognito. Carregue a grade usando o identificador gerado

Esperado: A grade horária deveria abrir

Real: O MatrUSP abre vazio

**Comment by brunoendo** [comment]
Pedro, quando puder da uma olhada que acho que está corrigido.

**Comment by pedropaulovc** [comment]
Confirmado.
