### ISSUE TITLE
Não é possível identificar qual a turma selecionada baseado na grade apresentada

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#24]
1. Monte uma grade. Ex. MAC2166, MAE0116 e MAT0111
2. Escolha uma combinação

Esperado: É possível identificar a turma que a combinação está usando para cada disciplina

Atual: Não há nenhuma informação visível ao usuário sobre a turma escolhida

**Comment by jyrodrigues** [comment]
Implementado.
