### ISSUE TITLE
MatrUSP fica lento ao adicionar 3 disciplinas com várias turmas

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#25]
1. No Edge
2. Monte uma grade com MAT0111, MAE0116 e MAC2166
3. Clique em cada combinação

Esperado: Uma vez que as combinações estão geradas, selecionar combinações deveria ser uma operação O(1)

Atual: Às vezes o MatrUSP engasga um pouco processando a seleção.

**Comment by Samlibardi** [comment]
Acredito que o problema seja devido ao fato de cada combinação criar um elemento no DOM. Para esse arranjo de disciplinas o #combination-track fica com 810 filhos e 82620px de largura.
Possível fix: utilizar um sistema de reciclagem de elementos (como o ListView do WPF e do android) para que o DOM não fique sobrecarregado de elementos. Talvez usar uma framework própria para criar esse tipo de estrutura.

EDIT: Alguns vídeos que ilustram o princípio:
https://www.youtube.com/watch?v=-VPM6ICgCk8
https://www.youtube.com/watch?v=LqBlYJTfLP4

**Comment by Samlibardi** [comment]
Fiz um teste de profiling, com a página carregada, apenas dando scroll nas combinações possíveis e selecionando combinações diferentes, em duas situações:

Apenas MAT0111 (9 combinações)
<img width="960" alt="2017-12-12 1" src="https://user-images.githubusercontent.com/29558451/33866391-a483b5b8-dedd-11e7-96b5-690b9c88eb16.png">

MAT0111, MAE0116 e MAC2166 (810 combinações)
<img width="960" alt="2017-12-12" src="https://user-images.githubusercontent.com/29558451/33866394-a76a26b8-dedd-11e7-95c9-7cf2b1f83c5b.png">

Da pra perceber que com essa quantidade de combinações o rendering toma muito tempo, quase 75% do tempo foi gasto com isso, enquanto pro primeiro caso, foram 5%

**Comment by pedropaulovc** [comment]
Ótima análise, concordo plenamente que esse é o problema. Agora, implementar reciclagem de elementos é algo bastante arriscado... Muitas chances de erros sutis que causam muita dor de cabeça, especialmente para contabilizar casos como quando usuários fazem scroll muito rápido ou quando a tela é redimensionada. Se a intenção é de corrigir o bug, eu preferiria que usássemos alguma biblioteca que faça o trabalho sujo. Me deixaria mais tranquilo que não vamos introduzir regressões no código.

**Comment by Samlibardi** [comment]
Sim, a implementação disso seria algo tão complexo quanto o projeto em si. Vou procurar se existem soluções prontas (acredito que existam).
Outras soluções menos elegantes seriam:
- Fixar em 5 as combinações mostradas e usar as setas já existentes para mudar a página
- Fixar um limite máximo (50 ou 100) para a quantidade de combinações mostradas e mostrar um aviso de que não foi possível carregar todas as combinações.

**Comment by Samlibardi** [comment]
Consegui substituir a maneira como as combinações são mostradas sem nenhuma alteração de UX substituindo toda a hierarquia de <divs> de cada combinação por um único <canvas> pintado uma única vez. Isso reduz o número enrome de cálculos de estilo e layout que o navegador tinha que fazer quando era aplicado o :hover ou quando o usuário fazia scroll. A performance de scroll no Chrome melhorou muito, no Firefox a performance já era boa, no Edge ainda não pude testar, mas acredito que tenha melhorado (é o navegador com mais dificuldades nesse aspecto)

EDIT: Testado no edge, a performance também teve uma melhora significativa

**Comment by pedropaulovc** [comment]
Issue resolvida! Mil obrigados ao @Samlibardi pelo fix!
