### ISSUE TITLE
Erro de digitação "disponibilisado"

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#27]
![image](https://cloud.githubusercontent.com/assets/577970/20314872/a53fc868-ab10-11e6-86f6-1fbacd85bae4.png)

Esperado: "Não disponibilizado pelo JupiterWeb"

**Comment by brunoendo** [comment]
Corrigido!

**Comment by pedropaulovc** [comment]
Você pode me apontar pro commit que corrigiu isso?

**Comment by brunoendo** [comment]
Claro, https://github.com/matrusp/matrusp/commit/ee68519445feb8751043a60214e25295cd9e64c7

**Comment by pedropaulovc** [comment]
Confirmado
