### ISSUE TITLE
Melhorar a exibição do nome de uma disciplina

### ISSUE THREAD

**Issue by jyrodrigues** [matrusp/matrusp#37]
Principalmente quando a disciplina está "fechada", às vezes (a depender do tamanho da tela), só é possível ver uma única palavra:

Não dá pra deixar assim:
![screen shot 2016-12-02 at 16 45 32](https://cloud.githubusercontent.com/assets/4342234/20846054/f6957c98-b8ae-11e6-899f-423ca44aa8d7.png)
(fechado)
![screen shot 2016-12-02 at 16 45 39](https://cloud.githubusercontent.com/assets/4342234/20846055/f696fc3a-b8ae-11e6-9c20-5a9d4239c429.png)
(aberto)

Opções:
- Utilizar [ellipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) quando estiver fechado
- Quebrar a palavra por hífen
- Diminuir os botões à direita

**Comment by pedropaulovc** [comment]
+1 Utilizar ellipsis quando estiver fechado
