### ISSUE TITLE
Mudar o algoritmo de busca de disciplinas

### ISSUE THREAD

**Issue by jyrodrigues** [matrusp/matrusp#39]
Mudar o "rankeamento" de disciplinas. Ao procurar, por exemplo, "proba", temos o seguinte:
![screen shot 2016-12-02 at 17 31 24](https://cloud.githubusercontent.com/assets/4342234/20847433/2f78a2c8-b8b5-11e6-9ddf-79f19421941e.png)
O `à` na primeira matéria faz com que ele seja rankeado acima da segunda, apesar dela ser muito parecida com a terceira.

Sugestão:
- Diminuir o _score_ da string para cada caracter que não foi pego pela regex. Com isso, strings grandes aparecerão depois de menores (em geral, nem sempre).

**Comment by jyrodrigues** [comment]
@brunoendo seu último commit (baaebe5) conserta isso? Não consegui olhar (problemas com o servidor local aqui).

**Comment by brunoendo** [comment]
Não, ele arruma a ordem que estava sendo ordenado a lista de sugestões
