### ISSUE TITLE
Adicionar a carga horária semanal

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#44]
Exibir na interface a carga horária semanal de uma grade de matrícula. Preferencialmente exibir em termos de créditos aula/trabalho. Se não for possível, exibir em termos de total de horas de aula por semana.

**Comment by brunoendo** [comment]
Pedro, você sabe qual é a conta para com a quantidade de horas achar a quantidade de créditos? Porque essa informação não está sendo pega pelo crawler.

**Comment by pedropaulovc** [comment]
O cálculo (número de horas) -> créditos não é confiável. Acho que o Júpiter
disponibiliza a o número certo na página de detalhes da disciplina.

Provavelmente foi por isso que eu acabei optando por mostrar só o número de
horas.

**Comment by brunoendo** [comment]
É foi o que eu pensei.

> Acho que o Júpiter disponibiliza a o número certo na página de detalhes da disciplina.

Disponibiliza sim! Vou verificar com o Heitor depois se o crawler que ele fez pega essas informações, e já começar a estudar o dele pra ver se já vale a pena utilizar o dele.

> Provavelmente foi por isso que eu acabei optando por mostrar só o número de horas.

Pode crer, assim que possível vejo se implemento isso.
