### ISSUE TITLE
Impossível salvar o identificador em uma tela de 800x600

### ISSUE THREAD

**Issue by giulianobelinassi** [matrusp/matrusp#45]
O que eu faço:
    - Abro o matrusp usando o Chromium em uma tela de 800x600.
    - Elaboro a minha grade no matrusp.
    - Tento salvar o meu identificador.

O que ocorre:
    - Não consigo clicar no campo "Salve o seu plano aqui".

O que eu espero que ocorra:
    - Que eu consiga clicar no campo para adicionar um identificador para em seguida clicar em "Salvar".

**Comment by brunoendo** [comment]
Olá, Giuliano,

Qual o motivo de você não conseguir clicar no campo? Aparece alguma outra informação por cima?

Se possível poderia mostrar uma foto

Abraço.

**Comment by giulianobelinassi** [comment]
Olá, Bruno.
    Sim, o campo de adicionar novas disciplinas fica sobreposto ao campo do identificador, conforme a imagem abaixo:

http://www.linux.ime.usp.br/~giulianob/matrusp_800.png

Abraços,
Giuliano.

**Comment by brunoendo** [comment]
Vlw Giuliano!

Vamos arrumar isso o mais rápido possível! Muito obrigado pela ajuda e o reporte do bug!

Abraço,
Bruno.

**Comment by phlfm** [comment]
Boa noite!
Tenho tido dificuldades com salvar / carregar meu plano no matrusp atual. É frequente ele apagar o plano do meu identificador ou não salvar.
