### ISSUE TITLE
MatrUSP não dá suporte a disciplinas com oferecimentos aos domingos

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#47]
1. Adicione EAD0740 - "Tópicos de Marketing" a uma grade do MatrUSP

Esperado: A disciplina deveria ser adicionada

Real: Exceção no código do MatrUSP. EAD0740 possui um oferecimento aos domingos.

**Comment by Samlibardi** [comment]
Adicionei um workaround no PR #75 que permite que essas disciplinas sejam adicionadas. É um fix parcial pois não adiciona o domingo na grade de fato, só ignora o horário de domingo.
