### ISSUE TITLE
Permutações de Grade Demoradas

### ISSUE THREAD

**Issue by phlfm** [matrusp/matrusp#52]
Ao marcar e desmarcar turmas há uma lentidão ao gerar as grades alternativas. Adicionar um timer para recalcular a cada X segundos ou até um botão para recalcular / check box pra desligar a atualização automática.

**Comment by pedropaulovc** [comment]
Você poderia detalhar quais disciplinas estão causando lentidão?


Obrigado
Pedro Paulo

**Comment by phlfm** [comment]
Boa noite, Paulo!
Não é uma disciplina em específico, mas sim quando há disciplinas com muitas turmas (geralmente com aulas no mesmo horário).
Por exemplo PCS3335 PEA3311... Quanto mais turmas disponíveis nas disciplinas, maior a lentidão ao mudar a checkbox para as turmas.

**Comment by jyrodrigues** [comment]
(Se me lembro bem) A forma como está feito é assim: a cada mudança na listagem das disciplinas (inclusão/exclusão, checkbox, mudança de prioridade) todas as combinações são recalculadas. Esse modelo é prático e fácil de ser implementado, mas ineficiente também.

A forma pela qual estas combinações são computadas, por sua vez, é bastante ineficiente também além de estar errada (issue #53). Remodelar essa estrutura pode unificar a solução destas duas issues.

Hoje em dia, a partir de um conjunto *fixo* de disciplinas calcula-se as diferentes combinações válidas, verificando *todas* as combinações possíveis (se temos N disciplinas com 2 turmas cada, testa-se 2^N combinações -- complexidade exponencial e péssima). Penso em um melhoramento em (potencialmente) duas etapas:

1) Alterar o algoritmo para executar com um perfil agregador. Com isto quero dizer o seguinte: começando com 2 disciplinas, encontra-se o conjunto de combinações válidas entre suas turmas (esse número será em muitos casos menor do que todas as combinações possíveis entre elas). Então analisa esse conjunto existente com mais uma disciplina e aumenta (ou diminui) esse conjunto; e continua assim por diante. Se não estou errado, desta forma a complexidade continua exponencial em uma análise de pior caso, mas evita-se a verificação de variações de combinações que já sabe-se serem inválidas, algo extremamente comum no nosso caso.

2) Alterar a estrutura lógica acerca deste algoritmo para tentar fazer apenas pequenas modificações no conjunto de combinações válidas no momento de uma mudança. Por exemplo, ao mudar a prioridade de uma disciplina, não recalcular todas as combinações, apenas reordená-las (mas ainda existe o caso em que uma disciplina não está incluída por conflito e ao ganhar prioridade é incluída, neste caso só a reordenação não é suficiente). O mesmo vale para a exclusão de disciplinas (lembrando que novas combinações também podem se tornar válidas por não existir mais conflito com a disciplina excluída).

O primeiro item, acho necessário e fácil de ser feito, já o segundo exige um pouco de análise sobre a estrutura geral do código e como as combinações serão armazenadas e não me parece tão simples (mas também não pensei muito sobre essa questão). Por exemplo, seria possível manter combinações válidas mas inativas que fizessem referência a uma disciplina com o checkbox desativado, assim não seria necessário recalcular nada ao re-selecioná-la (mas confesso que não sei se seria uma ideia boa fazer isso).

**Comment by phlfm** [comment]
> Alterar o algoritmo para executar com um perfil agregador

Além de ver as combinações entre disciplinas, acho que vale também agregar turmas diferentes no mesmo horário e tratá-las como um caso só.
Na poli temos muitas disciplinas com 4, 5, 6 turmas em que todas as turmas são dadas no mesmo horário, ou dadas em 2 ou 3 horários diferentes, não sendo necessário permutar 6 turmas e sim 3, 2 ou 1 horários.
