### ISSUE TITLE
Conflitos inexistentes

### ISSUE THREAD

**Issue by phlfm** [matrusp/matrusp#53]
O matrusp atual tem detectado conflitos inexistentes e ocultando disciplinas de forma desnecessária.
Vide no screenshot que PTC3307 e PSI3321 não são conflitantes porém apenas a de prioridade maior pode ficar acionada.
![screenshot_58](https://cloud.githubusercontent.com/assets/23559600/23381059/def04fa8-fd1b-11e6-8cb4-43a73267ce16.png)

**Comment by jyrodrigues** [comment]
Comentei sobre um possível caminho que solucionaria isso aqui #52.

**Comment by jyrodrigues** [comment]
Anexando o exemplo que a @barbarazip disponibilizou do bug na issue #55: 
[matrusp_2017.json.zip](https://github.com/matrusp/matrusp/files/1078495/matrusp_2017.json.zip)

**Comment by phlfm** [comment]
Novamente o mesmo bug. Ele não deixa selecionar PCS3111 pois ele alega conflito com PCS3446 na segunda feira, **mesmo havendo 4 horários NÃO conflitantes** ou mesmo desselecionando todas as turmas exceto uma (a de sexta de manhã, turma 09)

![image](https://user-images.githubusercontent.com/23559600/27814963-de496514-6056-11e7-9363-d4277105d3e2.png)

**Comment by pedropaulovc** [comment]
Outra lista de disciplinas. Eu notei que o problema apenas acontece com o Chrome.

Chrome:
![image](https://user-images.githubusercontent.com/577970/42304178-c501b608-7fd9-11e8-81f3-53fa0a08f93b.png)

Firefox:
![image](https://user-images.githubusercontent.com/577970/42304198-d24b88de-7fd9-11e8-986f-1fe0df14b9a0.png)

**Comment by Samlibardi** [comment]
> Outra lista de disciplinas. Eu notei que o problema apenas acontece com o Chrome.

Não consegui reproduzir o bug com esta lista no Chrome (69.0.3489.0 canary 64 bits). Todas as disciplinas funcionam normalmente. Consegui reparar que ocorre #52 ao marcar/desmarcar ou adicinar disciplinas já chegando ao fim da lista. Planejo trabalhar em reescrever o algoritmo de combinações (#30) incluindo as sugestões de agregar turmas idênticas que parece ser o grande causador deste enorme número de combinações.

PS. Reparei que o screenshot do Chrome está em uma versão mais antiga do MatrUSP. É possível que isso tenha alguma relação, mesmo eu não tendo mexido diretamente no cálculo de combinações

**Comment by pedropaulovc** [comment]
Mais uma instância:

FLC0114 turma 21
FLL0433 turma 23
FLC0112 turma 34
FLT0123 turma 12

**Comment by Samlibardi** [comment]
Pedro, não consegui reproduzir na versão mais recente.
________________________________

**Comment by pedropaulovc** [comment]
😮 . Por versão mais recente, você quer dizer a versão do PR #89 ou a versão em produção? A propósito, eu testei no Chrome, versão de produção depois que uma aluna reportou essa combinação como problemática.

**Comment by Samlibardi** [comment]
Testei apenas na versão do PR. Sendo assim acredito que deva ser o mesmo problema de antes, já corrigido.
________________________________

**Comment by pedropaulovc** [comment]
Maravilha!
