### ISSUE TITLE
O MATRUSP não monta a grade para mais do que 5 diciplinas

### ISSUE THREAD

**Issue by barbarazip** [matrusp/matrusp#55]
Estou tentando montar a grade com mais do que 5 disciplinas, porém a 6ª disciplina não entra, permanecendo desabilitada. Esse problema não ocorria na versão anterior. Já testei no Chrome e no Firefox e dá o mesmo problema em ambos.  A 6ª disciplina não entra em conflito com nenhuma outra, mas ainda assim não é adicionada. Ao inverter a ordem, ela entra, mas aquela que se torna a 6ª disciplina deixa de constar. 
Anexo o arquivo para verificação.
[matrusp_2017.json.zip](https://github.com/matrusp/matrusp/files/1078451/matrusp_2017.json.zip)

**Comment by jyrodrigues** [comment]
Oi Barbara,

Obrigado por abrir a issue! Estamos cientes deste bug (relatado na issue #53). Espero resolvê-lo em julho, mas ainda não consigo dizer se realmente terei tempo para isso. De qualquer forma, tentaremos consertar o quanto antes.

Abraços,
Zé
