### ISSUE TITLE
Bug no parser

### ISSUE THREAD

**Issue by wgnann** [matrusp/matrusp#56]
Olá,

O Matrusp devolve o professor errado para a disciplina MAT0265. Lá aparece a Lúcia Renato Junqueira enquanto no Júpiter (https://uspdigital.usp.br/jupiterweb/obterTurma?sgldis=MAT0265), a Lucia Satie Ikemoto Murakami.

Até! o/

**Comment by filipefilardi** [comment]
@wgnann 

Não cheguei a olhar o parser, mas o júpiter atualiza constantemente os professores, que as vezes trocam de turmas e disciplinas, enquanto o matrusp não. 

Acredito que não seja um bug, mas sim uma troca efetuada após a execução do parser (atualização do database do matrusp).

Abraços, o/

**Comment by pedropaulovc** [comment]
Como o Filipe falou, aparentemente o BD do MatrUSP estava desatualizado. Agora aparece corretamente.

![image](https://user-images.githubusercontent.com/577970/42298868-083caeea-7fbd-11e8-813d-d177dc28ef11.png)

![image](https://user-images.githubusercontent.com/577970/42298877-0f5adf4e-7fbd-11e8-8eb1-3b879470f54c.png)
