### ISSUE TITLE
Cadê as matéria

### ISSUE THREAD

**Issue by OrenjiAkira** [matrusp/matrusp#6]
Não tá teno matérias da fau. Sumiu.

Cadê

(serião to precisando, mim ajuda vaii)

**Comment by coelhodepina** [comment]
Oi William,

Qual disciplina?

O Matrusp só mostra disciplinas que parecem no Júpiter.

Muito obrigado,
coelho

**Comment by OrenjiAkira** [comment]
Oi, obrigado por responder :)
Todas as matérias de todos os departamentos da FAU sumiram. São as disciplinas de AUP, AUT e AUH. No júpiter consigo encontrá-las, mas no matrusp não.

**Comment by coelhodepina** [comment]
Oi William,

On Tue, Jun 21, 2016 at 12:51:57PM -0700, W. Akira Mizutani wrote:
> Oi, obrigado por responder :)
> Todas as matérias de todos os departamentos da FAU sumiram. São as disciplinas de AUP, AUT e AUH. No júpiter consigo encontrá-las, mas no matrusp não.

Vou rodar o script novamente.
Talvez elas tenha sido colocadas agora a tarde.
O Script que pega as disciplinas roda todo dia às 0h.


Muito obrigado,
coelho

**Comment by coelhodepina** [comment]
P.S.

Vou poderia me dar uma sigla de disciplina que você sabe
que será oferecida?

Muito obrigado,
coelho

**Comment by OrenjiAkira** [comment]
Dois exemplos são:
`AUP2316 Projeto Visual VIII - Ambiente/Cidade`
`AUH2816 Cultura Urbana na Contemporaneidade II`

**Comment by coelhodepina** [comment]
Oi William,

Muito obrigado.
O horário dessas disciplinas ainda não estão no Júpiter.
Assim que eles aparecem no Júpiter deverão aparecer no Matrusp.
As dos MAC só apareceram no Júpite hoje pala manhã.
Vou ficar monitorando e ver quando elas aparecerão no Júpiter.
Deverá sre hoje ou amanhã, acho...

Muito obrigado!
coelho

**Comment by OrenjiAkira** [comment]
Ah obrigado, então o problema é na fau mesmo.
Desculpa o incômodo e obrigado, Coelho :)

**Comment by coelhodepina** [comment]
Incômodo algum.
É bom avisar a gente pois o problema sempre pode ser com o Matrusp.

Muito obrigado,
coelho

**Comment by coelhodepina** [comment]
Hmmm.

Apesar da 1a. interação ter começado, ainda não vejo essas disciplinas
no Júpiter.

**Comment by OrenjiAkira** [comment]
Eu vi no jupiter, as disciplinas estao lá, porém sem oferecimento. Consegui até me matricular e tudo. Acho que a fau, como de costume, está atrasada em definir as turmas e os oferecimentos.
