### ISSUE TITLE
Fonte da database?

### ISSUE THREAD

**Issue by LeoColman** [matrusp/matrusp#64]
Onde posso encontrar a fonte da database das matérias do Matrusp? Por acaso o acesso é fácil? A modificação é feita dinamica ou manualmente?

Agradeço!

**Comment by Samlibardi** [comment]
A database é obtida diretamente do Jupiterweb por um crawler, configurado pra rodar uma vez por dia (eu acho).

**Comment by LeoColman** [comment]
Alguma chance de obter uma cópia disso?

**Comment by coelhodepina** [comment]
https://github.com/matrusp/matrusp/tree/tcc2016/old/py

prompt > python2 cron_update.py  ./db ./db/db_usp.txt

**Comment by LeoColman** [comment]
Incrível!

Obrigado.
