### ISSUE TITLE
Uso de SSL/TSL?

### ISSUE THREAD

**Issue by Samlibardi** [matrusp/matrusp#66]
Tenho trabalhado na implementação de Service Workers para o cache/uso offline do site. Por definição, só é possível utilizar Service Workers em conexões seguras (HTTPS) [(fonte)](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker). Além disso, o uso do appcache em domínios não seguros também não tem suporte, embora funcione normalmente por ora.

No [site principal da USP](https://www5.usp.br/) é utilizado um certificado wildcard válido para qualquer subdomínio .usp.br. No [site do IME](https://www.ime.usp.br/) é usado um certificado wildcard válido para qualquer domínio .ime.usp.br.  No entanto, o domínio do BCC não disponibiliza a conexão HTTPS. 
Acho importante levantar essa questão não só por causa do cache (claro), mas porque o uso de conexões seguras tem ganhado grande importância no padrão web. 

Não seria possível entrar em contato com o STI ou com o setor de TI do IME (não tenho conhecimento de quem é responsável pela manutenção dos servidores) para a aplicação do certificado SSL já existente no servidor do BCC (e quaisquer outros subdomínios do IME, porventura)?

Abraços

**Comment by pedropaulovc** [comment]
Olá Will,

Você sabe se o IME tem algum processo definido para habilitar SSL na
máquina BCC? Pensei em usar o Let's Encrypt, o que você acha?


Abraços
Pedro Paulo

2018-01-26 11:16 GMT-08:00 Samuel Libardi Godoy <notifications@github.com>:

**Comment by pedropaulovc** [comment]
Enviei um email para um dos admins da RedeIME para saber de mais detalhes.

**Comment by coelhodepina** [comment]
Por favor, vejam se está ok agora.

**Comment by pedropaulovc** [comment]
Confirmado. Ao acessar a versão HTTP fui redirecionado para HTTPS.
