### ISSUE TITLE
Erro de precisão em "Horas por Semana"

### ISSUE THREAD

**Issue by yancouto** [matrusp/matrusp#7]
![hora](https://cloud.githubusercontent.com/assets/3925674/16242019/e0723fa0-37c6-11e6-8c31-e0f2313ddb6d.png)
Estou fazendo 8 matérias de 1h40, então deveria ser 13h20.

**Comment by coelhodepina** [comment]
Oi Yan,

Muito obrigado por avisar.

té +,
coelho

**Comment by Samlibardi** [comment]
O contador de horas da versão antiga foi substituído por um contador de créditos baseado nas informações do Jupiter (#75). Isso não deve mais ser um problema.
