### ISSUE TITLE
Listagem do diretório /data

### ISSUE THREAD

**Issue by Samlibardi** [matrusp/matrusp#70]
O que acontece: O URL http://bcc.ime.usp.br/matrusp/data/ mostra um index com todos os arquivos na pasta data (states salvos por usuários)

O que deveria acontecer: Não mostrar nada (403).

Para arrumar: https://www.thesitewizard.com/apache/prevent-directory-listing-htaccess.shtml

**Comment by pedropaulovc** [comment]
Resolvido. Eu colquei um arquivo index.html. Quem tentar acessar o diretório terá uma surpresa desagradável. 😈
