### ISSUE TITLE
Exportar para .ics não está funcionando mais

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#71]
1. Carregue um identificador no MatrUSP
2. Clique para exportar para calendário. Escolha .ics

Esperado: Um download deveria começar.

Resultado:
TypeError: schedule.parent.classroomCode.replace is not a function icalendar.js:54:102
	generate_uid https://bcc.ime.usp.br/matrusp/js/icalendar.js:54:102
	build_event https://bcc.ime.usp.br/matrusp/js/icalendar.js:100:36
	download_icalendar https://bcc.ime.usp.br/matrusp/js/icalendar.js:118:105

**Comment by Samlibardi** [comment]
Olá. Já identifiquei a causa. Vou submeter um fix assim que possível.
