### ISSUE TITLE
Erro de redirecionamento HTTPS

### ISSUE THREAD

**Issue by Samlibardi** [matrusp/matrusp#74]
Percebi que quando o site é acessado pelo endereço HTTP, o seguinte erro é exibido: 

> SEC7120: [CORS] The origin 'http://bcc.ime.usp.br' did not find 'http://bcc.ime.usp.br' in the Access-Control-Allow-Origin response header for cross-origin  resource at 'https://bcc.ime.usp.br/matrusp/db/db_usp.txt'.

O que faz com que o banco de dados não seja atualizado para os clientes usando o endereço sem HTTPS.

Para consertar é necessário adicionar as seguintes configurações no Apache:

- No VHost HTTP (porta 80)
`Redirect permanent / https://bcc.ime.usp.br/matrusp/`

- No VHost HTTPS (porta 443)
`Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"`

De maneira que o navegador vai acessar o site usando TSL sempre (o redirecionamento funciona mesmo offline, com a versão em cache)

**Comment by pedropaulovc** [comment]
Olá Samuel, como você chegou nesse erro SEC7120? Ou, que browser não está funcionando? Eu tentei acessar o MatrUSP via Firefox e Edge via http e em ambos eu sou imediatamente redirecionado para a versão HTTPS.

**Comment by Samlibardi** [comment]
Havia notado o problema no Chrome, mas já não consigo reproduzir. 
No entanto, o header _Strict-Transport-Security_ ainda precisa ser habilitado, pois sem ele o navegador não redireciona automaticamente (offline) para a versão segura, o que faz que não seja possível acessar a versão em cache usando apenas o endereço bcc.ime.usp.br/matrusp sem o https://

**Comment by Samlibardi** [comment]
Além disso, para mim o Firefox está apresentando o erro de SSL SEC_ERROR_UNKNOWN_ISSUER impedindo o acesso ao site. Nos outros navegadores não há nenhum problema com o certificado SSL.

**Comment by pedropaulovc** [comment]
HTTP STS habilitado pelo PR 78.
