### ISSUE TITLE
A caixa de busca deve ser desabilitada enquanto o BD está sendo baixado

### ISSUE THREAD

**Issue by pedropaulovc** [matrusp/matrusp#82]
Estamos recebendo várias reclamações de alunos que estão tentando montar as suas grades no MatrUSP e nos avisam que não conseguem ver nenhuma disciplina no MatrUSP. Minha suspeita é que a interface carrega muito mais rápido que o BD e a barra de progresso é sutil demais para ser percebida.

![image](https://user-images.githubusercontent.com/577970/41659507-5aa61722-744e-11e8-8606-7be1fd55e34f.png)

Mudança esperada: Tal como no MatrUSP V1, enquanto o BD está sendo baixado, a caixa de busca deve ser desabilitada com uma mensagem "carregando..."

@Samlibardi você pode dar uma olhada neste bug?

**Comment by Samlibardi** [comment]
Uma das intenções quando decidi usar o indexedDB para guardar o BD foi de permitir que o usuário utilizasse a busca assim que entrasse - sem precisar esperar atualizar. O problema é que, pela maneira que foi implementado, disciplinas que já não estavam mais presentes continuavam salvas no BD e poderiam ficar lá por bastante tempo sem serem de fato válidas. Resolvi este problema limpando o BD antes de adicionar as disciplinas baixadas. Isso faz com que a leitura seja impossível enquanto a atualização acontece.
Vou achar um jeito de contornar isso e fazer com que as duas coisas sejam possíveis, mas é improvável que eu consiga terminar as mudanças ainda a tempo desta matrícula, então vou seguir a sugestão e tentarei implementar esse hotfix se possível até este fim de semana.

**Comment by Samlibardi** [comment]
Só pra confirmar: Após o carregamento concluir é possível adicionar as disciplinas? Algum usuário reportou as disciplinas nunca ficarem disponíveis? O carregamento não deve durar mais de 5 segundos em condições normais.

**Comment by pedropaulovc** [comment]
Eu consegui adicionar disciplinas após o BD carregar completamente e mudar alguns caracteres na caixa de busca. Eu considero uma experiência adequada. :)
