### ISSUE TITLE
Links no readme.md

### ISSUE THREAD

**Issue by wgnann** [matrusp/matrusp#84]
Tenho a impressão de que há links quebrados no readme:
  - a versão atual fica fora da USP?
  - a versão anterior é a versão atual na USP?
  - o matrusp v1 (do master) não deveria ser a versão anterior?
  - o cron_update.py referenciado no readme dá 404. não seria legal colocá-lo junto ao projeto? dei um clone, mas não o encontrei no branch.

**Comment by Samlibardi** [comment]
Obrigado por avisar, esquecemos de atualizar o readme após as mudanças. Já corrigi.
