### ISSUE TITLE
Setas ao lado de cada disciplina não funcionam corretamente

### ISSUE THREAD

**Issue by EnzoHideki** [matrusp/matrusp#85]
Setas ao lado de cada disciplina não funcionam sempre (e às vezes, as setas mudam a posição de outra disciplina).

**Comment by Samlibardi** [comment]
Obrigado pelo feedback! Já consegui isolar o problema e uma correção vai ser lançada em breve.

**Comment by Samlibardi** [comment]
Consertado no PR #83.
Mudanças já foram publicadas, deve estar tudo normal agora
