### ISSUE TITLE
Problema no parse_usp.py

### ISSUE THREAD

**Issue by wgnann** [matrusp/matrusp#86]
Tentei rodar o parse_usp.py e não funcionou. O Júpiter deve ter mudado o formato da página, daí ele não consegue terminar de montar os JSONs. O erro acusado foi justamente o da lista tds não ter nenhum elemento.

O trecho
`if re.search("Créditos\s+Aula:", tds[0], flags=re.U):`
acaba supondo que tds é sempre não-vazio.

Coloquei uma verificação antes para garantir que só faz sentido procurar pela regex quando o tds não é vazio e pareceu funcionar.

**Comment by Samlibardi** [comment]
Esse erro foi causado por uma página de créditos sem todas as informações, e aquela parte do código não tinha uma verificação para isso. Corrigi no PR #83, deve ser publicado logo
