### ISSUE TITLE
turma desaparecida 

### ISSUE THREAD

**Issue by wgnann** [matrusp/matrusp#87]
A turma 22 de EAE0205 está desaparecida. A parte mais curiosa é que ela aparece no JSON e as únicas diferenças entre uma e outra (no EAE0205.json) são o horário e os inscritos.

Subi uma versão do JSON aqui para facilitar.
[EAE0205.json.gz](https://github.com/matrusp/matrusp/files/2138972/EAE0205.json.gz)

Rodei
`$jq '.turmas[] ' EAE0205.json  -c  | wc -l`
e devolveu 4, como deveria.

Já na interface web aparecem apenas 3.

**Comment by pedropaulovc** [comment]
Resolvido pelo PR #83.
