### ISSUE TITLE
Sugestão: Opção de imprimir em preto e branco

### ISSUE THREAD

**Issue by bpbutti** [matrusp/matrusp#88]
Olá, 
acho que seria interessante implementar uma opção de salvar para pdf em preto e branco, pois assim fica viável imprimir em papel.
Fiz uma gambiarra no pdf.js e gerei esse dois pdfs hoje 
(transformei para png no gimp para facilitar a visualização)
![1-ed](https://user-images.githubusercontent.com/11468260/43501896-424aee0e-952e-11e8-84ca-a14dae3c52fc.png)
![2](https://user-images.githubusercontent.com/11468260/43501895-42092618-952e-11e8-9b87-2991aeba2b3b.png)

**Comment by Samlibardi** [comment]
Achei interessante essa sugestão, nunca havia reparado no problema que é imprimir a grade toda colorida. Acho que a parte de impressão como um todo merece uma atenção maior, com mais opções para imprimir e maior qualidade (dá pra perceber que as linhas da grade ficam fora de posição e a resolução não fica muito boa). Talvez para facilitar a identificação das disciplinas nesse modo econômico seja legal a substituição das cores por tons de cinza e padrões como traços e pontos, semelhante ao que é usado em mapas e gráficos em provas e artigos.
Se quiser enviar um PR com mudanças nesse sentido, será muito bem aceito.
