### ISSUE TITLE
Matérias da nova turma (2-45) de Ciência da Computação do IME não aparecem

### ISSUE THREAD

**Issue by danielkza** [matrusp/matrusp#9]
Vou cursar 3 matérias esse semestre, que aparecem no Júpiter como:

MAC0209-2-45
MAC0331-2-45
MAC0425-2-45

Nenhuma delas parece estar presente no Matrusp nesse momento.

**Comment by danielkza** [comment]
Ping @raverona que se prontificou a me ajudar!

**Comment by danielkza** [comment]
Olhando novamente, não tenho nenhuma matéria de MAC. Suspeito de algum problema com cache do browser, vou verificar.

**Comment by raverona** [comment]
Ao carregar uma grade com um identificador a seleção de semestre é desfeita e por isso o @danielkza  não estava vendo as matérias na busca, mas ao selecionar o semestre atual novamente as matérias são retornadas na busca normalmente.
